export const ADD_REMINDER = "ADD_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const CLEAN_REMINDERS = "CLEAN_REMINDERS";
export const REQUEST_DATA = "REQUEST_DATA";
export const RECEIVE_DATA = "RECEIVE_DATA";
export const REQUEST_FAILED = "REQUEST_FAILED";